### ISSUE TITLE
Next tasks for the simpleExchange dapp

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/dapp-simple-exchange#13]
The SimpleExchange dapp is now basically working, but has some rough edges. This is a list of obvious errors. What else do we need to work on?

 * [ ] completed orders don't appear in the order history (it stays blank)
 * [ ] The javascript console for the dapp UI reports 
      `Uncaught SyntaxError: Unexpected token '<'`
 * [ ] The javascript console for the dapp UI reports 
        `Warning: Each child in a list should have a unique "key" prop.` on line 1 of index.js
 * [ ] Dunno what causes this, but I've seen it a few times:
```
web: 127.0.0.1:52179[9]: inbound error: No handler for /api simpleExchange/subscribeRecentOrders from {
  "type": "simpleExchange/subscribeRecentOrders",
  "data": {},
  "meta": {
    "channelID": 9,
    "origin": "http://localhost:3000",
    "url": "/api",
    "date": 1587672221629
  }
}
```
 * [x] The errors below are logged in the console for `agoric start`when a contract is approved in the wallet UI.

```
agoric: install: removing ./node_modules
agoric: install: removing _agstate/agoric-servers/node_modules
agoric: install: removing api/node_modules
agoric: install: removing contract/node_modules
agoric: install: link SDK ./node_modules
agoric: install: link SDK _agstate/agoric-servers/node_modules
agoric: install: link SDK api/node_modules
agoric: install: link SDK contract/node_modules
agoric: install: link SDK _agstate/agoric-wallet
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.62s.
agoric: install: Done installing
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: initializing dev
SecurityWarning: '@agoric/harden' is ineffective without SES
agoric: start: setting sim chain with 0 second delay
SecurityWarning: '@agoric/harden' is ineffective without SES
agoric: start: linking html directories
SecurityWarning: '@agoric/harden' is ineffective without SES
launch-chain: Launching SwingSet kernel
web: Listening on 127.0.0.1:8000
start: swingset running
SwingSet: vat-wallet: Adding adminHandle Object <[Object: null prototype] {}> {
  dispatcher: 'onOpen',
  origin: 'http://localhost:8000',
  url: '/private/wallet',
  date: 1587577915262,
  channelHandle: [Object: null prototype] {
    toString: [Function (anonymous)] Function <Function <Complex prototype>>
  }
}
SwingSet: vat-zoe: LOGGED ERROR: key not found: Object <[Object: null prototype] {}> {} Error <Object <[Object: null prototype] {}>>: key not found: (an object)
See console for error data.
    at Object.complain (/SwingSet/vat-zoe/agoric-sdk/packages/assert/src/assert.js:162:21)
    at fail (/SwingSet/vat-zoe/agoric-sdk/packages/assert/src/assert.js:189:22)
    at Object.assert (/SwingSet/vat-zoe/agoric-sdk/packages/assert/src/assert.js:217:7)
    at assertKeyExists (/SwingSet/vat-zoe/agoric-sdk/packages/weak-store/src/weakStore.js:37:43)
    at Object.get (/SwingSet/vat-zoe/agoric-sdk/packages/weak-store/src/weakStore.js:46:9)
    at Object.getOfferNotifier (/SwingSet/vat-zoe/agoric-sdk/packages/zoe/src/zoe.js:613:51)
    at eval (/SwingSet/kernel/packages/SwingSet/src/kernel/liveSlots.js:350:25)
SwingSet: controller: UnhandledPromiseRejectionWarning: Error <Object <[Object: null prototype] {}>>: key not found: (an object)
See console for error data.
    at fullRevive (/SwingSet/kernel/packages/marshal/marshal.js:615:50)
    at Object.unserialize (/SwingSet/kernel/packages/marshal/marshal.js:663:21)
    at Object.notifyReject (/SwingSet/kernel/packages/SwingSet/src/kernel/liveSlots.js:444:21)
    at eval (/SwingSet/kernel/packages/SwingSet/src/kernel/vatManager.js:300:48)
SwingSet: vat-wallet: Removing adminHandle Object <[Object: null prototype] {}> {
  dispatcher: 'onClose',
  origin: 'http://localhost:8000',
  url: '/private/wallet',
  date: 1587578374076,
  channelHandle: [Object: null prototype] {
    toString: [Function (anonymous)] Function <Function <Complex prototype>>
  }
}
```

**Comment by Chris-Hibbert** [comment]
for the third bullet
 * [ ] The javascript console for the dapp UI reports
Warning: Each child in a list should have a unique "key" prop. on line 1 of index.js

OrderBook.jsx is trying to set a unique key
```
                  <TableRow key={order.publicID}>
```

If it's important enough to modify the simpleExchange contract, it could create an ID to accompany each offerHandle and include those in the bookOrders when it publishes them to the updater.

**Comment by katelynsills** [comment]
The dapp UI gets a string identifier back as the result of an 'walletAddOffer' message (the response is `type: 'walletOfferAdded',`). I think we should store that in the handler and use it as the publicID.

**Comment by michaelfig** [comment]
> The dapp UI gets a string identifier back as the result of an 'walletAddOffer' message (the response is `type: 'walletOfferAdded',`). I think we should store that in the handler and use it as the publicID.

We need publicIDs for every offer, not just the ones the current user submits.  They're used when determining how the orderbook has been updated, and if we're missing or changing the publicID, it causes unnecessary rerenders and stutters in the UI.

**Comment by katelynsills** [comment]
Oh very good point.

**Comment by michaelfig** [comment]
It would suffice just to use a monotonic offer counter per contract, and keep track of the offer's id number either in helpers or directly in the contract.

**Comment by Chris-Hibbert** [comment]
Another error I've seen occasionally, and don't have a causal description of yet: 
```
web: 127.0.0.1:52179[9]: inbound error: No handler for /api simpleExchange/subscribeRecentOrders from {
  "type": "simpleExchange/subscribeRecentOrders",
  "data": {},
  "meta": {
    "channelID": 9,
    "origin": "http://localhost:3000",
    "url": "/api",
    "date": 1587672221629
  }
}
```

**Comment by Chris-Hibbert** [comment]
> It would suffice just to use a monotonic offer counter per contract, and keep track of the offer's id number either in helpers or directly in the contract.

By the time the dapp gets the book orders from SimpleExchange, they don't have identity. It could use a fingerprint, but there's no reason to expect uniqueness.

The simpleExchange currently saves offerHandles. It could certainly assign a unique ID to each, and report those out with updates to the bookOrders. Once we do this, the UI can track orders it has seen that are no longer in the list, and show those in its history. I don't think it has a way to find out whether the ones that have gone missing were completed or cancelled. If you want to make a price history, you definitely want to limit it to completed offers.
